kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: development
  name: ROLE_DEV
rules:
- apiGroups: [""]
  resources: ["pods","deployments","services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-rolebinding
  namespace: development
subjects:
- kind: User
  name: dev_user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ROLE_DEV
  apiGroup: rbac.authorization.k8s.io