apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  type: NodePort

---
apiVersion: apps/v1     # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx-deployment
spec:
  selector:
      matchLabels:
        app: nginx
  serviceName: nginx
  # replicas: 2          # tells deployment to run 2 pods matching the template
  template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
          - name: nginx-store
            mountPath: /Users/jet/kubernetes/nginx
  volumeClaimTemplates:
  - metadata:
      name: nginx-store
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi