apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi #Size of the volume
  accessModes:
    - ReadWriteOnce #type of access
  hostPath:
    path: "/Users/jet/kubernetes/redis" 