apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: prod
data:
  password: root@root

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: prod
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/kubernetes/mysql
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: prod
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: prod
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  # replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD              #指定以mysql root 密码
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: mysql-config
              # Specify the key associated with the value
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      # securityContext:                            #指定以docker用户运行
      #   runAsUser: 1000
      #   runAsGroup: 1000
# ---
# 
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
#   namespace: prod
# spec:
#   selector:
#     app: mysql
#   type: NodePort
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306
#       nodePort: 30036